import { Link } from 'wouter';
import { SEO } from '@/components/seo';
import { JsonLd } from '@/components/json-ld';
import { SITE_URL, SITE_NAME } from '@/components/seo';
import { AUTHOR_NAME, AUTHOR_URL } from '@/lib/author';

function buildEditorialPolicySchema() {
  return {
    '@context': 'https://schema.org',
    '@type': 'WebPage',
    name: 'Editorial Policy | ToolBox',
    url: `${SITE_URL}/editorial-policy`,
    description:
      'How ToolBox creates and maintains its guides — accuracy standards, research process, update policy, and editorial purpose.',
    isPartOf: {
      '@type': 'WebSite',
      name: SITE_NAME,
      url: SITE_URL,
    },
  };
}

function buildEditorialBreadcrumbSchema() {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Home', item: SITE_URL },
      { '@type': 'ListItem', position: 2, name: 'Editorial Policy', item: `${SITE_URL}/editorial-policy` },
    ],
  };
}

const sections = [
  {
    id: 'purpose',
    heading: 'Purpose of This Website',
    body: `ToolBox publishes free, browser-based utility tools and plain-English guides that explain the mathematics, formulas, and logic behind everyday calculations. The goal is to help people understand — not just receive — an answer.

Every tool runs client-side in the user's browser. No data is transmitted to our servers, stored, or shared with third parties.`,
  },
  {
    id: 'how-guides-are-created',
    heading: 'How Guides Are Created',
    body: `Guides on ToolBox are written by ${AUTHOR_NAME}, a software engineer and technical writer with eight years of experience building online calculators and utilities.

Each guide is written from primary sources — published mathematical standards, official health guidelines (for BMI and similar topics), and peer-reviewed references where applicable. Guides are not generated by AI or syndicated from third-party content networks.

A typical guide includes:
- A clear explanation of the underlying formula or method
- Step-by-step worked examples with real numbers
- A quick-reference table or chart where useful
- A FAQ section addressing the most common misconceptions
- A link to the relevant free tool on ToolBox`,
  },
  {
    id: 'accuracy',
    heading: 'Accuracy Standards',
    body: `All formulas and numerical results published on ToolBox are verified against authoritative references before publication. For health-related content (BMI, for example), we follow the classifications published by the World Health Organization and the CDC.

If you believe any content on ToolBox is factually incorrect, please contact us immediately using the contact page. Corrections are applied within 48 hours of confirmation, and the guide's last-modified date is updated to reflect the change.`,
  },
  {
    id: 'update-process',
    heading: 'Update Process',
    body: `Guides are reviewed on a rolling basis — typically every six months — to check that formulas, classifications, and referenced standards remain current.

When a guide is updated for accuracy or completeness:
- The content is revised in full, not patched with footnotes
- The lastmod date in the sitemap is updated
- The dateModified field in the Article schema is updated

Minor changes such as correcting typographical errors or improving sentence clarity do not necessarily trigger a date update.`,
  },
  {
    id: 'independence',
    heading: 'Editorial Independence',
    body: `ToolBox has no sponsored content, affiliate links inside guides, or pay-to-publish arrangements. All tools and guides are produced independently, based solely on what is useful to readers.

The site displays advertising (served by Google AdSense). Advertising does not influence which tools are built, which topics are covered, or the content of any guide.`,
  },
  {
    id: 'contact',
    heading: 'Corrections & Feedback',
    body: `We take accuracy seriously. If you spot an error, an outdated figure, or a confusing explanation, please let us know using the contact form. All messages are read personally and responded to.`,
  },
];

export default function EditorialPolicy() {
  return (
    <>
      <SEO
        title="Editorial Policy | ToolBox"
        description="How ToolBox creates and maintains its guides — accuracy standards, research process, update policy, and editorial purpose."
      />
      <JsonLd id="editorial-policy-schema"    schema={buildEditorialPolicySchema()}    />
      <JsonLd id="editorial-breadcrumb-schema" schema={buildEditorialBreadcrumbSchema()} />

      {/* ── Page header ── */}
      <div className="border-b border-border bg-secondary">
        <div className="container mx-auto px-4 py-8 md:py-10 max-w-3xl">
          <nav aria-label="Breadcrumb" className="mb-4">
            <ol className="flex items-center gap-1.5 text-sm text-muted-foreground">
              <li><Link href="/" className="hover:text-foreground transition-colors">Home</Link></li>
              <li aria-hidden="true" className="text-border">›</li>
              <li className="text-foreground font-medium">Editorial Policy</li>
            </ol>
          </nav>
          <h1 className="text-2xl md:text-3xl font-bold text-foreground mb-2">Editorial Policy</h1>
          <p className="text-sm md:text-base text-muted-foreground leading-relaxed max-w-xl">
            How we create, verify, and maintain the guides on ToolBox.
          </p>
        </div>
      </div>

      {/* ── Content ── */}
      <div className="container mx-auto px-4 py-10 md:py-12 max-w-3xl">

        {/* Quick nav */}
        <nav className="border border-border rounded-md p-4 bg-secondary mb-10" aria-label="Page sections">
          <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-2">Contents</p>
          <ol className="space-y-1">
            {sections.map((s, i) => (
              <li key={s.id}>
                <a
                  href={`#${s.id}`}
                  className="text-sm text-foreground hover:text-primary transition-colors"
                >
                  {i + 1}. {s.heading}
                </a>
              </li>
            ))}
          </ol>
        </nav>

        {/* Sections */}
        <div className="space-y-0">
          {sections.map((section, idx) => (
            <section
              id={section.id}
              key={section.id}
              className={idx > 0 ? 'pt-8 mt-8 border-t border-border' : ''}
            >
              <h2 className="text-base font-semibold text-foreground mb-3">{section.heading}</h2>
              <div className="space-y-3">
                {section.body.split('\n').filter(Boolean).map((line, i) =>
                  line.startsWith('- ') ? null : (
                    <p key={i} className="text-sm text-muted-foreground leading-relaxed">
                      {line}
                    </p>
                  )
                )}
                {/* Bullet list items */}
                {(() => {
                  const bullets = section.body.split('\n').filter(l => l.startsWith('- '));
                  return bullets.length > 0 ? (
                    <ul className="space-y-1 pl-1">
                      {bullets.map((b, i) => (
                        <li key={i} className="flex items-start gap-2 text-sm text-muted-foreground">
                          <span className="text-primary mt-0.5 shrink-0">–</span>
                          {b.slice(2)}
                        </li>
                      ))}
                    </ul>
                  ) : null;
                })()}
              </div>
            </section>
          ))}
        </div>

        {/* Footer links */}
        <div className="mt-10 pt-8 border-t border-border flex flex-wrap gap-6 text-sm">
          <Link href={AUTHOR_URL} className="text-primary hover:underline underline-offset-4">
            About the author — {AUTHOR_NAME}
          </Link>
          <Link href="/about" className="text-primary hover:underline underline-offset-4">
            About ToolBox
          </Link>
          <Link href="/contact" className="text-primary hover:underline underline-offset-4">
            Contact us
          </Link>
        </div>

      </div>
    </>
  );
}
